server:
  port: 8010
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true

spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://106.52.119.32:3306/che_dan?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
